CREATE TABLE ootd_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    image_filename VARCHAR(100) NOT NULL,
    memo TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6)
);
