CREATE TABLE muscle_injuries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muscle_group VARCHAR(255) NOT NULL,
    injured_at TIMESTAMP(6) NOT NULL,
    recovered_at TIMESTAMP(6),
    CONSTRAINT muscle_injuries_muscle_group_check
        CHECK (muscle_group IN ('CHEST', 'BACK', 'LOWER_BODY', 'BICEPS', 'TRICEPS', 'SHOULDERS'))
);
