-- ddl-auto:update로 여기까지 쌓인 스키마의 스냅샷. baselineOnMigrate로 처리되므로 실제 실행되진 않고
-- "여기서부터 Flyway가 관리 시작함" 기준점 역할만 함 - 이후 스키마 변경은 V2부터 새 파일로 추가할 것
CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT categories_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying])::text[])))
);
ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.monthly_budgets (
    id bigint NOT NULL,
    amount numeric(38,2),
    month character varying(255) NOT NULL,
    savings_mode_enabled boolean DEFAULT false NOT NULL
);
ALTER TABLE public.monthly_budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monthly_budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.recurring_items (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL,
    day_of_month integer
);
ALTER TABLE public.recurring_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.routine_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    days_of_week character varying(255) NOT NULL,
    deleted_at timestamp(6) without time zone,
    memo character varying(255),
    title character varying(255) NOT NULL
);
ALTER TABLE public.routine_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routine_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.schedule_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    end_date date NOT NULL,
    memo character varying(255),
    start_date date NOT NULL,
    title character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'TODO'::character varying NOT NULL,
    routine_id bigint
);
ALTER TABLE public.schedule_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.todo_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    memo character varying(255),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    completed_at timestamp(6) without time zone,
    linked_schedule_item_id bigint,
    CONSTRAINT todo_items_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);
ALTER TABLE public.todo_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todo_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    description character varying(255),
    transaction_date date NOT NULL,
    type character varying(255) NOT NULL,
    category_id bigint NOT NULL,
    recurring_item_id bigint,
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying])::text[])))
);
ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.users (
    id bigint NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    monthly_budget numeric(38,2)
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.wishlist_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price numeric(38,2),
    priority character varying(255) NOT NULL,
    product_url character varying(255),
    linked_transaction_id bigint,
    purchased_at timestamp(6) without time zone,
    purchased boolean DEFAULT false NOT NULL,
    CONSTRAINT wishlist_items_priority_check CHECK (((priority)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[])))
);
ALTER TABLE public.wishlist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.monthly_budgets
    ADD CONSTRAINT monthly_budgets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recurring_items
    ADD CONSTRAINT recurring_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.routine_items
    ADD CONSTRAINT routine_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.schedule_items
    ADD CONSTRAINT schedule_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.todo_items
    ADD CONSTRAINT todo_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.monthly_budgets
    ADD CONSTRAINT uk5cpi62nk5v5r45diicrfvn78i UNIQUE (month);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.wishlist_items
    ADD CONSTRAINT wishlist_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recurring_items
    ADD CONSTRAINT fk7mbwtd7htaqp9kai4tx3olfiv FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fksqqi7sneo04kast0o138h19mv FOREIGN KEY (category_id) REFERENCES public.categories(id);
