ALTER TABLE notifications ADD COLUMN source_type VARCHAR(255) NOT NULL DEFAULT 'TODO';
ALTER TABLE notifications ADD COLUMN source_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN sent_for_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE notifications ALTER COLUMN source_type DROP DEFAULT;
ALTER TABLE notifications ALTER COLUMN source_id DROP DEFAULT;
ALTER TABLE notifications ALTER COLUMN sent_for_date DROP DEFAULT;
