CREATE TABLE workout_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_date DATE NOT NULL,
    muscle_group VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    memo VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT workout_records_muscle_group_check CHECK (muscle_group IN ('CHEST', 'BACK', 'LOWER_BODY', 'BICEPS', 'TRICEPS', 'SHOULDERS')),
    CONSTRAINT workout_records_status_check CHECK (status IN ('COMPLETED', 'INCOMPLETE', 'INJURED', 'SKIPPED'))
);

CREATE TABLE workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_record_id BIGINT NOT NULL REFERENCES workout_records(id),
    exercise_order INTEGER NOT NULL,
    exercise_name VARCHAR(255) NOT NULL
);

CREATE TABLE workout_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL REFERENCES workout_exercises(id),
    set_order INTEGER NOT NULL,
    weight_kg NUMERIC(6, 2),
    reps INTEGER NOT NULL
);
