CREATE TABLE saved_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL CHECK (type IN ('LINK', 'NOTE')),
    title VARCHAR(200) NOT NULL,
    url TEXT,
    content TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6)
);
