CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    address VARCHAR(300),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    category VARCHAR(100),
    place_url TEXT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('TO_VISIT', 'VISITED')),
    rating INTEGER,
    review TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6)
);
